In [16]:
#cd C:\Users\tr432\Desktop\Roh\Command\02. Python\06. Metabolomics\[KJW_Prof.]

In [31]:
import pandas as pd

from libs.preprocessing import MetaboPreprocer

import warnings
warnings.filterwarnings('ignore')

In [32]:
cd C:\Users\tr432\Downloads\Metabolomics_GutLungAxis_re-pipeline

C:\Users\tr432\Downloads\Metabolomics_GutLungAxis_re-pipeline

In [33]:
# The dataset (ecpect "labels" and "Name" class) must not contain non-numeric values
# Columns of "Name" and "Label" must be included in the dataset (please refer the README.md)
# Labels class in blank naming must be 'blank', not "Blank", "B", 'b'...
# .xlsx or .csv file are only allowed in this analysis process.

original_dataset = pd.read_excel('Compounds_merged.xlsx', sheet_name='serum_pos_tp')
original_dataset.head(3)

,Name,Label,286.31052-14.933,127.03897-1.441,258.27917-14.002,61.03969-1.062,496.33995-14.389,172.07169-4.382,520.34-13.811,73.06478-1.434,...,437.22062-12.514,420.039-9.53,674.89818-0.956,288.86105-0.885,277.20115-13.158,363.27442-15.162,316.18052-7.669,290.8553-0.999,361.88999-0.954,243.88082-0.929
0,BL1,blank,2.553798e+09,2.408801e+09,1.052799e+09,1.606881e+07,6.844526e+06,1.157801e+06,4.665339e+06,9.523904e+08,...,174564.003914,45120.025106,31511.869455,36918.812811,82015.991455,86558.270894,44153.105968,27466.673498,31892.667997,27957.952011
1,BL2,blank,7.353271e+08,3.093175e+08,3.085743e+08,1.156592e+07,7.209158e+06,1.979458e+06,4.026565e+06,9.213781e+08,...,41042.848642,178917.414417,26491.062875,35870.846374,132482.017757,58748.373735,84248.202332,29747.949939,26811.188539,25098.232082
2,BL3,blank,2.343091e+09,2.138201e+08,1.066110e+09,1.341865e+07,7.519924e+06,4.812889e+05,3.482413e+06,9.780546e+08,...,84279.159043,80750.705953,28004.036185,35433.944654,141314.379995,78779.828343,140399.253679,29046.808985,28342.445056,24752.054175

In [34]:
# "step_blank_substracte" and "step_filter_rsd" are data filtering step
# The steps of data filtering are able to remove useless features
# This step is strongly recommended for untargeted metabolomics dataset with large numbers of features

# step_blank_substration : Substracte the blank values from the original intensities and remove features with a large number of negative data
# step_filter_rsd        : Features with high percent RSD can be removed from the dataset. Filtering the features based on RSD of QC 

# RSD = standard devication / mean
# QC = quality control

preprocesser = MetaboPreprocer(
    step_blank_substrateion=True,
    step_filter_rsd=False,
#    filter_ratio=0.3,
    qc_label='QC',
    scaling='log_pareto',
    file_save=True,
#    criteria_ND_proportion=0.5
)

In [35]:
'''
# df_scaled = scaled and filtered (if step_blank_subtration or step_filter_rsd is True) dataset
# df_ori = only filtered dataset


df_scaled, df_ori = preprocesser.preprocessing(
    'Compounds_merged.xlsx',
    sheet_name='serum_pos_tp',
)

df_scaled.head(3)
'''

"\n# df_scaled = scaled and filtered (if step_blank_subtration or step_filter_rsd is True) dataset\n# df_ori = only filtered dataset\n\n\ndf_scaled, df_ori = preprocesser.preprocessing(\n    'Compounds_merged.xlsx',\n    sheet_name='serum_pos_tp',\n)\n\ndf_scaled.head(3)\n"

In [ ]:
# 0w

df_scaled, df_ori = preprocesser.preprocessing(
    'Compounds_merged.xlsx',
    sheet_name='fecal_pos_tp',
    label_list= ['Control_0w', 'VNAM_0w']
)

df_scaled.head(3)

=========== Preprocessing ==========
Original dataset shape (n_samples, n_features + 2) = (77, 13587)
A total of 0 missing values were detected
========== Substrate the blank intensity from raw(original) intensity ==========
Removal of featuers with more than 50.0% proportion of negative values in all groups
Before the substration process, dataset shape (n_samples, n_features + 2) = (77, 13587).
After the substration process, dataset shape (n_samples, n_features + 2) = (67, 13109).
========== Label Selectioin ==========
['Control_0w', 'VNAM_0w'] features are selected and scaled
2 features have all zero values. These featuers are removed
Processed dataset shape (n_samples, n_features + 2) = (15, 13107)

,Name,Label,132.10187-1.793,86.09628-1.791,265.1118-1.078,166.08621-3.166,60.04447-16.937,132.10193-1.494,297.27878-16.919,120.08073-3.155,...,182.19021-13.573,171.0652-7.474,197.09212-7.014,311.18556-13.449,83.04907-17.088,209.11695-12.53,152.11821-17.7,171.13801-10.682,141.14676-17.763,179.16241-17.614
0,C03_0w,Control_0w,0.714129,0.759252,0.140523,0.669023,1.072727,0.841842,0.488631,0.587419,...,-1.504773,1.354829,-0.745428,-1.118568,-1.484132,-0.018336,0.936766,-1.471838,1.092909,-0.905766
1,C04_0w,Control_0w,0.281534,0.429301,0.401400,0.243925,1.159248,0.264115,1.087947,0.399023,...,-1.504773,1.617486,0.541426,-1.118568,1.435058,-0.391718,1.349334,-1.471838,-1.466179,-0.905766
2,C05_0w,Control_0w,0.605608,0.679321,0.036082,0.586938,-3.991942,0.737124,0.600737,0.638187,...,-1.504773,-2.000694,0.753961,-1.118568,-1.484132,-0.354860,1.086217,-1.471838,1.650320,-0.905766

In [23]:
# 1w

df_scaled, df_ori = preprocesser.preprocessing(
    'Compounds_merged.xlsx',
    sheet_name='fecal_pos_tp',
    label_list= ['Control_1w', 'VNAM_1w']
)

df_scaled.head(3)

=========== Preprocessing ==========
Original dataset shape (n_samples, n_features + 2) = (77, 13587)
A total of 0 missing values were detected
========== Substrate the blank intensity from raw(original) intensity ==========
Removal of featuers with more than 50.0% proportion of negative values in all groups
Before the substration process, dataset shape (n_samples, n_features + 2) = (77, 13587).
After the substration process, dataset shape (n_samples, n_features + 2) = (67, 13109).
========== Label Selectioin ==========
['Control_1w', 'VNAM_1w'] features are selected and scaled
Processed dataset shape (n_samples, n_features + 2) = (21, 13109)

,Name,Label,132.10187-1.793,86.09628-1.791,265.1118-1.078,166.08621-3.166,60.04447-16.937,132.10193-1.494,297.27878-16.919,120.08073-3.155,...,182.19021-13.573,171.0652-7.474,197.09212-7.014,311.18556-13.449,83.04907-17.088,209.11695-12.53,152.11821-17.7,171.13801-10.682,141.14676-17.763,179.16241-17.614
0,C01_1w,Control_1w,0.566060,0.638899,-0.041976,0.522011,2.177700,0.028873,0.518866,0.536105,...,-0.551163,-1.858781,0.734010,1.868087,-2.215532,-0.393494,-1.709953,-1.232006,1.348006,3.147998
1,C02_1w,Control_1w,0.854821,0.774880,0.340103,0.907008,2.134435,0.787628,0.921108,0.918072,...,-0.551163,1.409544,0.689452,-1.453746,-2.215532,0.222169,1.413869,-1.232006,1.180828,-0.696968
2,C03_1w,Control_1w,0.636697,0.660817,0.124884,0.632618,-2.335457,0.510738,0.722455,0.628446,...,-0.551163,-1.858781,-0.153539,-1.453746,1.829759,-0.613688,1.420036,-1.232006,1.161144,2.914538

In [36]:
# 2w

df_scaled, df_ori = preprocesser.preprocessing(
    'Compounds_merged.xlsx',
    sheet_name='serum_pos_tp',
    label_list= ['Control_2w', 'VNAM_2w']
)

df_scaled.head(3)

=========== Preprocessing ==========
Original dataset shape (n_samples, n_features + 2) = (21, 1928)
A total of 0 missing values were detected
========== Substrate the blank intensity from raw(original) intensity ==========
Removal of featuers with more than 50.0% proportion of negative values in all groups
Before the substration process, dataset shape (n_samples, n_features + 2) = (21, 1928).
After the substration process, dataset shape (n_samples, n_features + 2) = (18, 1675).
========== Label Selectioin ==========
['Control_2w', 'VNAM_2w'] features are selected and scaled
Processed dataset shape (n_samples, n_features + 2) = (15, 1675)

,Name,Label,61.03969-1.062,496.33995-14.389,172.07169-4.382,520.34-13.811,73.06478-1.434,79.02112-1.1,203.05255-1.03,522.35575-14.699,...,596.29997-13.718,437.22062-12.514,674.89818-0.956,288.86105-0.885,277.20115-13.158,363.27442-15.162,316.18052-7.669,290.8553-0.999,361.88999-0.954,243.88082-0.929
0,C03_2w,Control_2w,-0.094717,0.228524,-1.710834,0.376894,0.341940,-1.737609,0.418406,0.525424,...,0.265819,-2.075964,0.276760,0.035956,-0.890636,0.951327,-1.045299,-1.067158,0.227399,0.069099
1,C04_2w,Control_2w,-0.055197,0.180054,-1.710834,0.199344,0.668576,-1.737609,0.229619,0.327473,...,0.175870,0.954281,-0.504293,0.260620,2.049838,-1.810144,1.785516,0.399323,-0.031577,-0.791695
2,C05_2w,Control_2w,-0.281101,0.112347,-1.710834,0.044692,0.656013,-1.737609,0.407263,0.145407,...,0.278866,0.395425,-0.524646,0.404390,-0.890636,1.210122,-1.045299,0.072491,0.184948,-0.473356