Before importing the Python libraries in the cell below, run the following command to access the `libs` directory from the local path :

```python
cd C:\Github_repository\Metabolomics_Tutorial
```

In [9]:
#cd C:\Github_repository\Metabolomics_Tutorial

In [6]:
import pandas as pd

from libs.preprocessing import MetaboPreprocer

import warnings
warnings.filterwarnings('ignore')

In [ ]:
cd C:\Github_repository\Metabolomics_Tutorial\Data

In [8]:
# The dataset (expect "labels" and "Name" class) must not contain non-numeric values
# Columns of "Name" and "Label" must be included in the dataset
# Labels class in blank naming must be 'blank', not "Blank", "B", 'b'...
# .xlsx or .csv file are only allowed in this analysis process.

original_dataset = pd.read_excel('Compounds_merged.xlsx', sheet_name='fecal_neg_tp')  #Edit
original_dataset.head(3)

,Name,Label,296.61697-8.708,487.23704-10.048,421.22633-15.475,134.89469-16.398,421.22647-16.397,197.80811-1.288,134.8947-16.053,296.61713-13.231,...,555.02091-1.006,318.8747-0.972,454.84771-0.969,107.90717-0.945,187.02236-1.021,520.83183-0.955,356.91342-0.925,127.00133-1,443.23-9.348,111.08159-9.143
0,BL1,blank,3.050975e+08,67782.193316,4.777520e+09,2.142431e+09,1.687702e+08,6.688440e+08,5.139073e+08,8.740116e+07,...,14840.367739,13204.760207,12185.791235,15670.186378,17898.609383,8919.031901,14065.068548,14605.456286,6852.144074,11566.179604
1,BL2,blank,2.441851e+08,68640.603518,5.295591e+09,1.102732e+09,1.816002e+08,6.163625e+08,5.495560e+08,8.065268e+07,...,14810.837213,14114.038259,13024.903218,15744.776728,17897.553088,9533.195265,14431.061747,14576.393205,5980.761393,16047.393212
2,BL3,blank,2.547846e+08,131920.154644,5.626814e+09,3.652175e+08,2.038520e+08,6.037269e+08,1.194490e+09,7.750460e+07,...,15149.226047,14829.088002,13684.774867,15642.449788,16922.996247,9309.270159,14207.751912,15316.318851,6566.693629,18756.513809

In [9]:
# "step_blank_substracte" and "step_filter_rsd" are data filtering step
# The steps of data filtering are able to remove useless features
# This step is strongly recommended for untargeted metabolomics dataset with large numbers of features

# step_blank_substration : Substract the blank values from the original intensities and remove features with a large number of negative data
# step_filter_rsd        : Features with high percent RSD can be removed from the dataset. Filtering the features based on RSD of QC 

# RSD = standard devication / mean
# QC = quality control

preprocesser = MetaboPreprocer(
    step_blank_substrateion=True,
    step_filter_rsd=False,
#    filter_ratio=0.3,
    qc_label='QC',
    scaling='log_pareto',
    file_save=True,
#    criteria_ND_proportion=0.5
)  #Edit

It is recommended to create folders in the `SampleType_SamplingWeek` structure in advance and move the files generated for each time point into the corresponding folder.

For example, place `dataset_filtered_scaled.csv` and `dataset_filtered.csv` in the fecal_neg/0w folder.

In [10]:
# 0w

df_scaled, df_ori = preprocesser.preprocessing(
    'Compounds_merged.xlsx',
    sheet_name='fecal_neg_tp',
    label_list= ['Control_0w', 'VNAM_0w']  #Edit: if your label list is different, change ['Control_0w', 'VNAM_0w'] to the appropriate labels in your dataset.
)

df_scaled.head(3)

=========== Preprocessing ==========
Original dataset shape (n_samples, n_features + 2) = (77, 9087)
A total of 0 missing values were detected
========== Substrate the blank intensity from raw(original) intensity ==========
Removal of featuers with more than 50.0% proportion of negative values in all groups
Before the substration process, dataset shape (n_samples, n_features + 2) = (77, 9087).
After the substration process, dataset shape (n_samples, n_features + 2) = (67, 8572).
========== Label Selectioin ==========
['Control_0w', 'VNAM_0w'] features are selected and scaled
Processed dataset shape (n_samples, n_features + 2) = (15, 8572)

,Name,Label,296.61697-8.708,487.23704-10.048,134.89469-16.398,421.22647-16.397,296.61713-13.231,197.8081-1.761,134.89467-16.9,421.22642-15.939,...,555.02091-1.006,318.8747-0.972,454.84771-0.969,107.90717-0.945,187.02236-1.021,520.83183-0.955,356.91342-0.925,127.00133-1,443.23-9.348,111.08159-9.143
0,C03_0w,Control_0w,1.618325,1.046590,0.292804,0.856170,2.132992,1.062945,0.330459,1.791888,...,0.759275,0.553142,0.534385,-0.995816,0.410430,-0.800984,0.229668,0.720037,0.361410,1.100896
1,C04_0w,Control_0w,1.563632,-1.509677,-1.027665,-0.134522,2.118834,1.287277,-0.205233,1.465699,...,0.249890,-2.121149,1.254936,1.880237,0.955772,-0.800984,0.045110,1.293984,-0.550691,0.892698
2,C05_0w,Control_0w,1.474107,0.971783,-0.260028,-0.272271,2.018145,1.533738,0.174739,-2.472871,...,0.018429,0.287405,0.245161,-0.995816,0.412398,-0.800984,-1.175770,0.186202,-0.592785,-1.940296

In [11]:
# 1w

df_scaled, df_ori = preprocesser.preprocessing(
    'Compounds_merged.xlsx',
    sheet_name='fecal_neg_tp',
    label_list= ['Control_1w', 'VNAM_1w']    #Edit: if your label list is different, change ['Control_1w', 'VNAM_1w'] to the appropriate labels in your dataset.
)

df_scaled.head(3)

=========== Preprocessing ==========
Original dataset shape (n_samples, n_features + 2) = (77, 9087)
A total of 0 missing values were detected
========== Substrate the blank intensity from raw(original) intensity ==========
Removal of featuers with more than 50.0% proportion of negative values in all groups
Before the substration process, dataset shape (n_samples, n_features + 2) = (77, 9087).
After the substration process, dataset shape (n_samples, n_features + 2) = (67, 8572).
========== Label Selectioin ==========
['Control_1w', 'VNAM_1w'] features are selected and scaled
1 features have all zero values. These featuers are removed
Processed dataset shape (n_samples, n_features + 2) = (21, 8571)

,Name,Label,296.61697-8.708,487.23704-10.048,134.89469-16.398,421.22647-16.397,296.61713-13.231,197.8081-1.761,134.89467-16.9,421.22642-15.939,...,555.02091-1.006,318.8747-0.972,454.84771-0.969,107.90717-0.945,187.02236-1.021,520.83183-0.955,356.91342-0.925,127.00133-1,443.23-9.348,111.08159-9.143
0,C01_1w,Control_1w,-2.658636,0.400967,0.321571,0.816091,-1.237774,2.150835,0.164575,1.357300,...,-2.754963,-1.986167,1.285873,-0.498989,-1.243583,-1.510948,-0.216558,-2.744651,-0.621765,1.166865
1,C02_1w,Control_1w,-2.658636,-0.027972,0.231757,0.106637,-1.237774,-1.756985,0.487127,1.463895,...,0.481008,-1.986167,-2.330672,-0.498989,0.621839,-1.510948,0.030724,0.506659,-0.467709,1.329989
2,C03_1w,Control_1w,0.869260,0.298059,0.183581,-0.663269,-1.237774,2.654981,0.478400,-2.836131,...,-0.156501,-1.986167,-2.330672,-0.498989,0.164478,-1.510948,-0.077808,-0.155420,-0.350510,0.834750

In [12]:
# 2w

df_scaled, df_ori = preprocesser.preprocessing(
    'Compounds_merged.xlsx',
    sheet_name='fecal_neg_tp',
    label_list= ['Control_2w', 'VNAM_2w']    #Edit: if your label list is different, change ['Control_2w', 'VNAM_2w'] to the appropriate labels in your dataset.
)

df_scaled.head(3)

=========== Preprocessing ==========
Original dataset shape (n_samples, n_features + 2) = (77, 9087)
A total of 0 missing values were detected
========== Substrate the blank intensity from raw(original) intensity ==========
Removal of featuers with more than 50.0% proportion of negative values in all groups
Before the substration process, dataset shape (n_samples, n_features + 2) = (77, 9087).
After the substration process, dataset shape (n_samples, n_features + 2) = (67, 8572).
========== Label Selectioin ==========
['Control_2w', 'VNAM_2w'] features are selected and scaled
1 features have all zero values. These featuers are removed
Processed dataset shape (n_samples, n_features + 2) = (21, 8571)

,Name,Label,296.61697-8.708,487.23704-10.048,134.89469-16.398,421.22647-16.397,296.61713-13.231,197.8081-1.761,134.89467-16.9,421.22642-15.939,...,291.73107-0.859,555.02091-1.006,318.8747-0.972,454.84771-0.969,187.02236-1.021,520.83183-0.955,356.91342-0.925,127.00133-1,443.23-9.348,111.08159-9.143
0,C01_2w,Control_2w,-4.572774,0.067086,1.110949,-0.208549,-2.462796,1.956116,0.444313,1.407484,...,0.843714,0.293503,0.421251,0.289999,-0.303579,0.156101,0.725600,0.405881,-1.493018,0.620932
1,C02_2w,Control_2w,0.223411,0.453396,-0.553325,-0.280528,-2.462796,1.923118,0.130061,1.481465,...,0.868264,0.625360,0.990746,0.338911,0.376839,0.534191,-0.122333,0.729615,-0.778087,-0.137926
2,C03_2w,Control_2w,0.657662,0.402793,-1.168239,-1.001226,-2.462796,2.182810,0.343078,-2.843410,...,0.929613,0.158100,-2.623551,1.171263,0.328093,-1.894465,0.264382,0.889764,-0.536311,-3.498776